# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DALDfCwp1MtBDJKDZz4ecyhx3XjiVH2p
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
df = pd.read_csv("crop_yield_data_large.csv")
print(df.head())
# Encode 'Crop' (categorical) into numerical
le = LabelEncoder()
df['Crop'] = le.fit_transform(df['Crop'])  # Wheat=1, Rice=0 (or vice versa)

# Features & target
X = df.drop("Crop_Yield (ton/ha)", axis=1)
y = df["Crop_Yield (ton/ha)"]
plt.figure(figsize=(8, 5))
sns.histplot(df["Crop_Yield (ton/ha)"], bins=20, kde=True, color='green')
plt.title("Distribution of Crop Yield")
plt.xlabel("Yield (ton/ha)")
plt.ylabel("Frequency")
plt.show()